name: 'Dependabot Jira Sync'

# Example workflow showing how to use the Dependabot Jira Sync action
# This workflow syncs Dependabot security alerts to Jira issues with
# configurable due dates based on severity levels.

on:
  schedule:
    # Run every 6 hours to check for new alerts
    - cron: '0 */6 * * *'

  workflow_dispatch:
    # Allow manual triggering
    inputs:
      dry-run:
        description: 'Run in dry-run mode (no actual changes)'
        required: false
        type: boolean
        default: false

permissions:
  # Required permissions for the action
  security-events: read
  contents: read

jobs:
  sync-dependabot-alerts:
    runs-on: ubuntu-latest
    name: Sync Dependabot Alerts to Jira

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: npm

      - name: Install dependencies and build
        run: |
          npm ci
          npm run package

      - name: Sync Dependabot Alerts to Jira
        id: sync
        uses: threemonkeysconsulting/dependabot-jira-sync-action@v1.0.0 # Use published stable version
        with:
          # GitHub Authentication - Choose ONE method:

          # Option 1: GitHub App (Recommended)
          github-app-id: ${{ secrets.DEPENDABOT_APP_ID }}
          github-app-private-key: ${{ secrets.DEPENDABOT_APP_PRIVATE_KEY }}
          github-app-installation-id:
            ${{ secrets.DEPENDABOT_APP_INSTALLATION_ID }}

          # Option 2: Personal Access Token (Alternative)
          # github-token: ${{ secrets.DEPENDABOT_PAT }}

          # Jira Configuration (Required)
          jira-url: ${{ secrets.JIRA_URL || vars.JIRA_URL }}
          jira-username: ${{ secrets.JIRA_USERNAME || vars.JIRA_USERNAME }}
          jira-api-token: ${{ secrets.JIRA_API_TOKEN }}
          jira-project-key:
            ${{ secrets.JIRA_PROJECT_KEY || vars.JIRA_PROJECT_KEY }}

          # Jira Issue Configuration (Optional)
          jira-labels: 'dependabot,security,auto-created'

          # Severity-Based Due Dates (Optional)
          # Configure how quickly different severity issues should be addressed
          critical-due-days: '7' # Critical: Fix within 7 days
          high-due-days: '14' # High: Fix within 14 days
          medium-due-days: '30' # Medium: Fix within 30 days
          low-due-days: '90' # Low: Fix within 90 days

          # Filter Configuration (Optional)
          severity-threshold: 'medium' # Only process medium+ severity alerts
          exclude-dismissed: 'true' # Skip alerts that have been dismissed

          # Behavior Configuration (Optional)
          update-existing: 'true' # Update existing Jira issues when alerts change
          dry-run: ${{ inputs.dry-run || 'false' }} # Use input parameter for dry-run

      - name: Print Summary
        if: always()
        run: |
          echo "## Dependabot Jira Sync Summary" >> $GITHUB_STEP_SUMMARY
          echo "- **Issues Created:** ${{ steps.sync.outputs.issues-created || 'N/A' }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Issues Updated:** ${{ steps.sync.outputs.issues-updated || 'N/A' }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Alerts Processed:** ${{ steps.sync.outputs.alerts-processed || 'N/A' }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Summary:** ${{ steps.sync.outputs.summary || 'No summary available' }}" >> $GITHUB_STEP_SUMMARY
